docker stop memcached
docker rm memcached
docker stop rabbitmq
docker rm rabbitmq
docker stop mongodb
docker rm mongodb
docker stop retrievaldb
docker rm retrievaldb
docker stop db
docker rm db
docker stop backup_postgis
docker rm backup_postgis
docker stop backup_retrieval
docker rm backup_retrieval
docker stop backup_mongo
docker rm backup_mongo
docker stop iip
docker rm iip
docker stop ims
docker rm ims
docker stop core
docker rm core
docker stop retrieval
docker rm retrieval
docker stop nginx
docker rm nginx
