docker stop memcached1
docker rm memcached1
docker stop memcached2
docker rm memcached2
docker stop memcached3
docker rm memcached3
docker stop memcached4
docker rm memcached4
docker stop rabbitmq
docker rm rabbitmq
docker stop mongodb
docker rm mongodb
docker stop retrievaldb
docker rm retrievaldb
docker stop db
docker rm db
docker stop backup_postgis
docker rm backup_postgis
docker stop backup_retrieval
docker rm backup_retrieval
docker stop backup_mongo
docker rm backup_mongo
docker stop iipOff
docker rm iipOff
docker stop iipCyto
docker rm iipCyto
docker stop iipVent
docker rm iipVent
docker stop iipJ2
docker rm iipJ2
docker stop ims
docker rm ims
docker stop core
docker rm core
docker stop retrieval
docker rm retrieval
docker stop nginx
docker rm nginx
