#!/bin/bash
### BEGIN INIT INFO
# Provides:          iip
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: IIP Image Servers Init Scripts
# Description:       Launch and stop serveral iip image server instances
#                    
### END INIT INFO

# IIP Startup Service script v1.0 by STEVENS Benjamin 21 November 2012
# acts as startup service script for IIP Image servers.
# USAGE: start|stop|status|logs
#
case "$1" in
start)
echo "Starting IIP Image servers."
/opt/cytomine/bin/start-iip.sh
;;
stop)
echo "Stopping IIP Image Servers."
/opt/cytomine/bin/stop-iip.sh
;;
logs)
echo "See the logs of the IIP Image Servers."
tail -f /opt/cytomine/logs/iip.out
;;
status)
# Check to see if the process is running
ps aux|grep -i iip
;;
*)
echo "IIP Image Servers Service"
echo $"Usage: $0 {start|stop|status|logs}"
exit 1
esac
exit 0
