#!/bin/bash
#
# Copyright (c) 2009-2017. Authors: see NOTICE file.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
### BEGIN INIT INFO
# Provides:          iip
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: IIP Image Servers Init Scripts
# Description:       Launch and stop serveral iip image server instances
#                    
### END INIT INFO

# IIP Startup Service script v1.0 by STEVENS Benjamin 21 November 2012
# acts as startup service script for IIP Image servers.
# USAGE: start|stop|status|logs
#
case "$1" in
start)
echo "Starting IIP Image servers."
/opt/cytomine/bin/start-iip.sh
;;
stop)
echo "Stopping IIP Image Servers."
/opt/cytomine/bin/stop-iip.sh
;;
logs)
echo "See the logs of the IIP Image Servers."
tail -f /opt/cytomine/logs/iip.out
;;
status)
# Check to see if the process is running
ps aux|grep -i iip
;;
*)
echo "IIP Image Servers Service"
echo $"Usage: $0 {start|stop|status|logs}"
exit 1
esac
exit 0
